### ISSUE TITLE
unexpected field name change from message log after upgrade to v4.2.0

### ISSUE THREAD

**Issue by genofire** [kube-logging/logging-operator#1353] opened 2023-06-06 15:39 UTC
**Describe the bug**:
Before v4.2.0 unparsed logs appear in `message`, there are in `log` now.

**Expected behaviour**:
Logs are still in `message`

**Steps to reproduce the bug**:
- update operator (keep pinned tag of fluentd)

**Additional context**:
the problem are in fluentbit (because we still use old fluentd version).

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- logging-operator version (e.g. 2.1.1): 4.2.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by pepov** [comment] 2023-06-07 11:15
I will need some time to verify where it changed exactly because we did not change anything in the operator.

For those who are bitten by this:
- you can explicitly tell the fluentd parsers/filters which key to use
- you can downgrade to previous fluentbit version (logging operator 4.1.0 used fluentbit 1.9.10)
- you can override the parser using the new custom parser feature see: https://github.com/kube-logging/logging-operator/blob/master/config/samples/containerd-merge-log.yaml#L17-L34

If anyone can verify or dig deeper in the meantime, it would be extremely helpful

**Comment by pepov** [comment] 2023-06-08 10:31
The problem is not with single/multiline, but rather that the original parsers.conf is not available inside the image with logging operator version 4.2.0, because we accidentally overwrite it with a volume mount. Fluentbit then falls back to a different parser automatically (fortunately or unfortunately - it depends)

Preparing a fix right now.

**Comment by pepov** [comment] 2023-06-09 08:52
Fix is in `4.2.1` (image and helm chart)

**Closed by pepov** 2023-06-09 08:52 UTC
Labels: bug
