### ISSUE TITLE
Elastic Index Lifecycle Management not working as expected

### ISSUE THREAD

**Issue by volleynator** [kube-logging/logging-operator#799] opened 2021-08-03 15:06 UTC
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
I want my indices to be rolled over regularly by using Elastic ILM policies. However, the ilm policy defined in my clusterOutput is not respected.

**Expected behaviour**:
ILM is created by logging-operator-logging

**Steps to reproduce the bug**:
These are the values of my logging-operator-logging helm chart:
```
# Reference name of the logging deployment
loggingRef: ""
# Disable configuration check before deploy
flowConfigCheckDisabled: false
# Use static configuration instead of generated config.
flowConfigOverride:	""

nameOverride: ""
fullnameOverride: ""

# If an immutable field is changed, delete the existing resource
# and recreate it with the new configuration.
enableRecreateWorkloadOnImmutableFieldChange: false

# Fluent-bit configurations https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluent-bit-spec
fluentbit:
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

#Node agent Definition
nodeAgents: {}

# Fluentd configurations https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluentd-spec
fluentd:
  logLevel: debug
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 256Mi

  bufferStorageVolume:
    pvc:
      spec:
        resources:
          requests:
            storage: 10Gi

# Enable secure connection between fluentd and fluent-bit
tls:
  enabled: false
  # Shared key for fluentd authentication
  sharedKey: ""
  fluentbitSecretName: ""
  fluentdSecretName: ""

# Limit namespaces from where to read Flow and Output specs
watchNamespaces: []
# Control namespace that contains ClusterOutput and ClusterFlow resources
controlNamespace: ""

# defaultFlow
defaultFlow: {}

# defaultFlow
globalFilters: []

# ClusterOutputs to deploy
clusterOutputs:
  - name: es-output
    spec:
      elasticsearch:
        host: elasticsearch-master.logging.svc.cluster.local
        port: 9200
        scheme: http
        ssl_verify: false
        ssl_version: TLSv1_2
        buffer:
          timekey: 1m
          timekey_wait: 30s
          timekey_use_utc: true
        index_name: "e7-logs"
        include_timestamp: true
        logstash_format: false
        application_name: e7
        index_date_pattern: "now/w{xxxx.ww}"
        enable_ilm: true
        rollover_index: true
        ilm_policy_id: "fluentd-policy"
        ilm_policy: '{"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_size":"4gb","max_age":"7d","max_primary_shard_size":"2gb"}}},"cold":{"min_age":"7d","actions":{"set_priority":{"priority":0}}},"delete":{"min_age":"30d","actions":{"delete":{}}}}}}'
        # template_name: "e7-logs-template"
        data_stream_enable: true
        data_stream_name: "e7-stream"

clusterFlows:
  - name: es-output
    spec:
      filters:
       - dedot:
           de_dot_separator: "-"
           de_dot_nested: true
      globalOutputRefs:
        - es-output
```

**Additional context**:
Elastic Index Management tells me there is a stream defined and a ilm policy, however, the policy is not equals the defined policy inside my values.yaml

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): DigitalOcean
- logging-operator version (e.g. 2.1.1): 3.12.0
- logging-operator-logging version (e.g. 2.1.1): 3.9.5
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by ahma** [comment] 2021-10-17 17:51
Hi @volleynator thanks for the report sorry for the late reply , can you confirm this issue is still exist with the current version ?

**Comment by naviat** [comment] 2022-10-31 08:46
Sorry for any inconvenience, Do you have any solution to fix the issue? @volleynator

**Comment by jadhavnitind** [comment] 2022-11-29 17:09
Do we have any fix for this issue?

**Comment by dedops** [comment] 2023-04-06 11:08
No fix yet?

**Comment by pepov** [comment] 2023-04-11 12:43
The logging operator is only generating a config for fluentd. Please check the fluentd configuration and verify it is what you would expect. If it's not then it's a config generation issue and we (or anyone) can fix it.
If it's what you would expect than it's a fluentd plugin issue. I'm working on cleaning up and prepping a new image version for fluentd v1.15 with ruby version 3, I will update and you can give it a try.

**Comment by pepov** [comment] 2023-04-17 16:54
Please try this with the following image: `ghcr.io/kube-logging/fluentd:v1.15-staging`

**Comment by kobejn-jb** [comment] 2023-05-12 09:41
Hey @pepov, I'm having similar issues, for me fluentd created ILM policy first time I've tried it but it didn't when I've tried to add more outputs with different policies. I've tried to use `ghcr.io/kube-logging/fluentd:v1.15-staging` but now fluentd pod fails because of a gem conflict:
```
/usr/lib/ruby/3.1.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate fluent-plugin-elasticsearch-5.2.5, because faraday-2.7.4 conflicts with faraday (~> 1.10) (Gem::ConflictError)
        from /usr/lib/ruby/3.1.0/rubygems/specification.rb:1419:in `activate'
        from /usr/lib/ruby/3.1.0/rubygems.rb:211:in `rescue in try_activate'
        from /usr/lib/ruby/3.1.0/rubygems.rb:204:in `try_activate'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:153:in `rescue in require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch.rb:20:in `<top (required)>'
        from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch_data_stream.rb:2:in `require_relative'
        from /usr/lib/ruby/gems/3.1.0/gems/fluent-plugin-elasticsearch-5.2.5/lib/fluent/plugin/out_elasticsearch_data_stream.rb:2:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/registry.rb:103:in `block in search'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/registry.rb:100:in `each'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/registry.rb:100:in `search'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/registry.rb:44:in `lookup'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin.rb:169:in `new_impl'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/plugin.rb:114:in `new_output'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:130:in `add_match'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:74:in `block in configure'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:64:in `each'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/agent.rb:64:in `configure'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/label.rb:31:in `configure'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:146:in `block in configure'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:146:in `each'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/root_agent.rb:146:in `configure'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/engine.rb:105:in `configure'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/engine.rb:80:in `run_configure'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/supervisor.rb:731:in `run_supervisor'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/lib/fluent/command/fluentd.rb:350:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/gems/3.1.0/gems/fluentd-1.15.3/bin/fluentd:15:in `<top (required)>'
        from /usr/bin/fluentd:25:in `load'
        from /usr/bin/fluentd:25:in `<main>'
```

**Comment by pepov** [comment] 2023-05-22 19:59
the above issue with `ghcr.io/kube-logging/fluentd:v1.15-staging` had been fixed, can you try with it again?

**Comment by kobejn-jb** [comment] 2023-05-23 10:16
Thank you, the image does start correctly but still ILM policies are not created, I've created issue in `fluent-plugin-elasticsearch` repo, I believe root cause of my issue is in the plugin

**Comment by pepov** [comment] 2023-05-26 06:51
thanks for checking, I will close this issue, but let me know if we help on the operator side with anything

**Closed by pepov** 2023-05-26 06:51 UTC
Labels: bug
